from models import State
from a_star import *

joao_pessoa = State("João Pessoa")
campina_grande = State("Campina Grande")
itabaiana = State("Itabaiana")
santa_rita = State("Santa Rita")
mamanguape = State("Mamanguape")
guarabira = State("Guarabira")
areia = State("Areia")
picui = State("Picui")
soledade = State("Soledade")
coxixola = State("Coxixola")
patos = State("Patos")
monteiro = State("Monteiro")
catole = State("Catolé do Rocha")
pombal = State("Pombal")
itaporanga = State("Itaporanga")
sousa = State("Sousa")
cajazeiras = State("Cajazeiras")

joao_pessoa.add_neighbours([campina_grande, itabaiana, santa_rita])
campina_grande.add_neighbours([joao_pessoa, itabaiana, areia, coxixola, soledade])
itabaiana.add_neighbours([joao_pessoa, campina_grande])
santa_rita.add_neighbours([joao_pessoa, mamanguape])
mamanguape.add_neighbours([santa_rita, guarabira])
guarabira.add_neighbours([mamanguape, areia])
areia.add_neighbours([guarabira, campina_grande])
picui.add_neighbours([soledade])
soledade.add_neighbours([campina_grande, patos, picui])
coxixola.add_neighbours([campina_grande, monteiro])
patos.add_neighbours([soledade, pombal, itaporanga])
monteiro.add_neighboursadd_neighbours([coxixola, itaporanga])
catole.add_neighbours([pombal])
pombal.add_neighbours([catole, patos, sousa])
itaporanga.add_neighbours([patos, monteiro])
sousa.add_neighbours([pombal, cajazeiras])

search(joao_pessoa, pombal)
